# gitlab-ci

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  PLAN: plan.tfplan
  VARS: sample.tfvars

stages:
  - plan

before_script:
  - terraform --version
  - terraform init

plan:
  stage: plan
  script:
    - terraform validate -var-file=$VARS
    - terraform plan -out=$PLAN -var-file=$VARS

after_script:
  - ls -alh
